language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"